name: Deploy to Production

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  NODE_VERSION: '20'

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      build-cache-key: ${{ steps.cache-key.outputs.value }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Generate cache key
        id: cache-key
        run: echo "value=${{ github.sha }}-${{ github.run_id }}" >> $GITHUB_OUTPUT

      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: |
            node_modules
            apps/*/node_modules
            .bun
          key: deps-${{ runner.os }}-${{ hashFiles('**/package.json', '**/bun.lockb') }}
          restore-keys: |
            deps-${{ runner.os }}-

      - name: Install dependencies
        run: bun install

      - name: Build types
        run: bun run build:types

      - name: Check types
        run: bun run check-types

      - name: Build applications
        run: bun run build

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: |
            apps/web/dist
            apps/server/dist

  migrate-database:
    needs: build
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Download build artifacts
        uses: actions/download-artifact@v4
        with:
          name: build-artifacts

      - name: Install dependencies
        run: bun install

      - name: Run database migrations
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          cd apps/server
          bun run db:migrate

  notify:
    needs: [migrate-database]
    runs-on: ubuntu-latest
    if: always()
    
    steps:
      - name: Notify deployment success
        if: needs.migrate-database.result == 'success'
        run: |
          echo "✅ Deployment completed successfully!"
          echo "🗄️ Database migrations applied"

      - name: Notify deployment failure
        if: needs.migrate-database.result == 'failure'
        run: |
          echo "❌ Deployment failed!"
          echo "Database migration status: ${{ needs.migrate-database.result }}"
          echo "Please check the logs for more details." 